### ISSUE TITLE
Resource links

### ISSUE THREAD

**Issue by Avallex** [carloscds/HtmlToPDFCore#3]
Hi,

Had a quick play around, seems conversion of relative reference URLs to absolute references isn't supported by the converter.

I.e.: "../img/jjw_logo_transparent.png" or for sake of Mvc "~/img/jjw_logo_transparent.png"

If this is doable and could be added it would be a massive, massive help.

Thanks!

**Comment by Avallex** [comment]
If anybody is using .NET Core Mvc then using simple regular expressions you can replace the relative references that way:

![image](https://user-images.githubusercontent.com/30622420/127485393-5786a0e7-e595-42b3-9c1c-61522f2ba7db.png)

**Comment by carloscds** [comment]
Hi @Avallex ,
This tool do not look for HTML content, only convert HTML to PDF, maybe you can do this before call converter.

**Comment by Avallex** [comment]
That's okay, I've done that with regex, thanks for the quick reply!
