### ISSUE TITLE
Run the error report in docker...

### ISSUE THREAD

**Issue by Silence12345** [carloscds/HtmlToPDFCore#8]
Exception: /app/rotativa/Linux/wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory

**Comment by Silence12345** [comment]
help me 😭

**Comment by carloscds** [comment]
@Silence12345 You nee to install dependencies insiode your container.

**Comment by Silence12345** [comment]
Is there any documentation I can refer to?

**Comment by carloscds** [comment]
@Silence12345 Look at this: https://www.cyberciti.biz/faq/debian-ubuntu-linux-wkhtmltopdf-error-while-loading-shared-libraries-libxrender-so-1/
