### ISSUE TITLE
Disabling smart shrinking

### ISSUE THREAD

**Issue by marcinszynkowski** [carloscds/HtmlToPDFCore#9]
Thanks for the simple and nice library.
Is there any option to disable smart shrinking? Pdf looks ok but the problem is that there is some useless empty space and not fill 
A4 page.

**Comment by carloscds** [comment]
@marcinszynkowski I have only PageMargins. Can you provide a sample about this ?

**Comment by marcinszynkowski** [comment]
> @marcinszynkowski I have only PageMargins. Can you provide a sample about this ?

My pdf looks something like this :
[https://pasteboard.co/oNm1WpDcsSHq.png](url)

The rectangle with black border is my pdf content, and all the white is the A4-size.
PageMargins gives me only the effect that the content is sticking to left up corner.
Rotativa is based on wkhtml which is cmd-line tool, which has a switch "--disable-smart-shrinking".
I needed a library which converts html into pdf and works in docker, and your library works but the problem is this white blank space I don't need.

**Comment by carloscds** [comment]
@marcinszynkowski I created an option to disdable smart shrinking. This update broke compatibility with .NET Standard 2.0

**Comment by marcinszynkowski** [comment]
> @marcinszynkowski I created an option to disdable smart shrinking. This update broke compatibility with .NET Standard 2.0

Thank you very much! It works like a charm :)
